VP-26|feat(gui): added block objects
Ecodrin/RLReversi pull request #11
Opened 2024-04-09 16:03 UTC by Ecodrin

Block objects added

2024-04-09 19:38 UTC, anxiousss reviewed
Фикси, пока без такоса

2024-04-09 19:38 UTC, anxiousss commented on src/gui_elements.py
> +        for obj in self.__content:
use enumerate

2024-04-09 19:38 UTC, anxiousss commented on src/gui_elements.py
> +        for obj in self.__content:
use enumerate

2024-04-09 19:38 UTC, anxiousss commented on src/gui_elements.py
> +            # двигаем подвижную координаты
???

2024-04-09 19:38 UTC, anxiousss commented on src/gui_elements.py
> +            if obj.hitbox[amendment] + obj.hitbox[amendment + 2] > self.__borders[amendment] + self.__borders[amendment + 2]\
что с переносом

2024-04-10 10:46 UTC, anxiousss commented on src/gui_elements.py
> +            ind += 1
https://younglinux.info/python/feature/enumerate

2024-04-10 10:46 UTC, anxiousss commented on src/gui_elements.py
> +            # двигаем подвижную координату
???????

2024-04-10 10:50 UTC, anxiousss requested changes

2024-04-10 10:50 UTC, anxiousss commented on src/gui_elements.py
> +    def __str__(self) -> str:
repr перед str

2024-04-10 11:21 UTC, Ke1thuzad requested changes
Комментарии в прошлый файлах на русском, сделай здесь тоже на русском. Комментарий должен начинаться с большой буквы и оканчиваться точкой (по PEP8).

2024-04-10 11:21 UTC, Ke1thuzad commented on src/gui_elements.py
> +    def __init__(self, content: list[Any],
Или tuple

2024-04-10 11:21 UTC, Ke1thuzad commented on src/gui_elements.py
> +        self.__content: list[Any] = content
Тоже самое

2024-04-10 11:21 UTC, Ke1thuzad commented on src/gui_elements.py
> +                 margins: tuple[int, int] = (0, 0)) -> None:
Или list

2024-04-10 11:21 UTC, Ke1thuzad commented on src/gui_elements.py
> +        self.__margins: tuple[int, int] = margins
+

2024-04-10 11:21 UTC, Ke1thuzad commented on src/gui_elements.py
> +        Class for draw objects in the box
```suggestion
        Класс для отрисовки группы объектов в ряд с заданными отступами.
```

2024-04-10 11:21 UTC, Ke1thuzad commented on src/gui_elements.py
> +        :param borders: borders of block and its position
position, а не borders.

2024-04-10 11:21 UTC, Ke1thuzad commented on src/gui_elements.py
> +        :param margins: margin: int  of pixels between elements.
???
массив отступов

2024-04-10 11:21 UTC, Ke1thuzad commented on src/gui_elements.py
> +        self.__count_draw_object: int = 0
Почему инкапсуляция на всех объектах (даже без property)? У тебя должны быть публичные переменные.

2024-04-10 11:21 UTC, Ke1thuzad commented on src/gui_elements.py
> +        if isinstance(value, tuple) == 0:
или list

2024-04-10 11:21 UTC, Ke1thuzad commented on src/gui_elements.py
> +        return wrapper
Зачем писать лишний код, если можно в конце каждой функции вызывать self.__create_block()???????

2024-04-10 11:21 UTC, Ke1thuzad commented on src/gui_elements.py
> +    def insert(self, pos: int, obj: Any) -> None:
Не сокращай переменные

2024-04-10 11:21 UTC, Ke1thuzad commented on src/gui_elements.py
> +        for obj in self.__content:
match case, handle exceptions

2024-04-10 11:21 UTC, Ke1thuzad commented on src/gui_elements.py
> +            obj.hitbox = center_relative_to(element=obj.hitbox, relative_to=self.__borders, mode=self.__direction)
Ты должен центровать в противоположную ось.
Блок вертикальный - центрирование по горизонтали.

2024-04-10 11:21 UTC, Ke1thuzad commented on src/gui_elements.py
> +            amendment = 1
У тебя смещение в 1 направлении, зачем создавать бесполезный вектор, если можно смещать по 1 координате?

2024-04-10 11:21 UTC, Ke1thuzad commented on src/gui_elements.py
> +                 margins: tuple[int, int] = (0, 0)) -> None:
Не margins, а margin. Check Jira

2024-04-10 11:21 UTC, Ke1thuzad commented on src/gui_elements.py
> +            amendment = 1
И переменные имеют плохие названия.

2024-04-10 11:21 UTC, Ke1thuzad commented on src/gui_utility.py
> +                       margins: tuple | list = (0, 0, 0, 0)) -> Any | None:
None - подмножество Any.

2024-04-10 11:21 UTC, Ke1thuzad commented on src/gui_elements.py
> +            # центруем по заданной оси
```suggestion
            # Центрируем по заданной оси
```

2024-04-10 11:21 UTC, Ke1thuzad commented on src/gui_elements.py
> +        if self.__direction == 'horizontally':
Направление - существительное.
Horizontal/Vertical (direction)

2024-04-10 11:21 UTC, Ke1thuzad commented on src/gui_elements.py
> +        if isinstance(value, tuple) == 0:
Используй not вместо == 0, у тебя bool.

2024-04-10 11:21 UTC, Ke1thuzad commented on src/gui_elements.py
> +        if isinstance(value, str) == 0:
Тоже bool.

2024-04-10 11:21 UTC, Ke1thuzad commented on src/gui_elements.py
> +                 direction: str = 'horizontally',
Существительное (см. коммент. ниже)

2024-04-10 20:04 UTC, Ke1thuzad requested changes
Комментарии хотя бы с большой буквы сделай и попонятнее.

2024-04-10 20:04 UTC, Ke1thuzad commented on src/gui_elements.py
>          self.__count_draw_object: int = 0
Не все переменные должны быть приватными.

2024-04-10 20:04 UTC, Ke1thuzad commented on src/gui_elements.py
> +        return self.__count_draw_object
Зачем?

2024-04-10 20:04 UTC, Ke1thuzad commented on src/gui_elements.py
> +    def insert(self, pos: int, obj: Any) -> None:
???

2024-04-10 20:04 UTC, Ke1thuzad commented on src/gui_elements.py
> +                amendment = 1
amendment никак не связан с математикой. Поменяй название переменных.

2024-04-10 20:04 UTC, Ke1thuzad commented on src/gui_elements.py
> +            # двигаем подвижную координату
????

2024-04-10 20:04 UTC, Ke1thuzad commented on src/gui_elements.py
>              # проверяем, вышло ли за стенку
За границу*
Большая буква в начале где?

2024-04-10 20:04 UTC, Ke1thuzad commented on src/gui_elements.py
>              # увеличиваем приращение
тоже самое

2024-04-10 20:04 UTC, Ke1thuzad commented on src/gui_elements.py
> +        :param event: event
Раньше было лучше. Русский язык еще.

2024-04-10 20:04 UTC, Ke1thuzad commented on src/gui_elements.py
>              i += 1
enumerate ???

2024-04-10 20:04 UTC, Ke1thuzad commented on src/gui_elements.py
> +                margin_amendment = self.__position[0] + self.__position[0]
???

2024-04-10 20:04 UTC, Ke1thuzad commented on src/gui_elements.py
> +                    self.__position[amendment + 2] + self.__margin[amendment]):
Ничерта не понятно. Комментарии?

2024-04-10 20:04 UTC, Ke1thuzad commented on src/gui_elements.py
> +                 margin: tuple[int, int] | list[int, int] = (0, 0)) -> None:
Ладно возвращай margins, может, в будущем будет полезно для диагональных групп.

2024-04-10 20:06 UTC, Ecodrin commented on src/gui_elements.py
> +                    self.__position[amendment + 2] + self.__margin[amendment]):
на строчку выше посмотри

2024-04-11 08:10 UTC, anxiousss approved these changes

2024-04-11 18:56 UTC, Ke1thuzad requested changes

2024-04-11 18:56 UTC, Ke1thuzad commented on src/gui_elements.py
> +            raise TypeError('')
Где ошибка?

2024-04-11 18:56 UTC, Ke1thuzad commented on src/gui_elements.py
> +            raise TypeError('Margins must be a list | tuple type')
Вместо |   or пиши

2024-04-11 18:56 UTC, Ke1thuzad commented on src/gui_elements.py
> +    def insert(self, position: int, obj: Any) -> None:
Не сокращай переменные...

2024-04-11 18:56 UTC, Ke1thuzad commented on src/gui_elements.py
>                  amendment = 0
Я просил изменить название...

2024-04-11 18:56 UTC, Ke1thuzad commented on src/gui_elements.py
> +                shift = self.__position[1] + self.__margins[1]
Очень понятно что делает эта строка...
Особенно индексирование помогает!!!!

2024-04-11 18:56 UTC, Ke1thuzad commented on src/gui_elements.py
> +                shift = self.__position[0] + self.__margins[0]
Очень понятно что делает эта строка...
Особенно индексирование помогает!!!!

2024-04-11 18:56 UTC, Ke1thuzad commented on src/gui_elements.py
> +            # Двигаем по оси.
КАКОЙ? ЗАЧЕМ? ПОЧЕМУ?

2024-04-11 18:56 UTC, Ke1thuzad commented on src/gui_elements.py
> +            # Проверяем, вышло ли за границу (длина объекта + координата его левого угла >= границы блока).
У тебя в коде не >=...

2024-04-11 18:56 UTC, Ke1thuzad commented on src/gui_elements.py
> +                    self.__position[amendment + 2] + self.__margins[amendment]):
Очень очевидно значение "... + 2"

2024-04-11 18:56 UTC, Ke1thuzad commented on src/gui_elements.py
> +            shift += self.__margins[amendment] + obj.hitbox[amendment + 2]
Тоже супер очевидно.
Обожаю обращение по индексам массивов

2024-04-11 18:56 UTC, Ke1thuzad commented on src/gui_elements.py
> +        Клик момент
Скорее Bruh moment.
Меняй.

2024-04-11 18:56 UTC, Ke1thuzad commented on src/gui_elements.py
> +        :param event: момент
какой момент...
клей?

2024-04-11 18:56 UTC, Ke1thuzad commented on src/gui_elements.py
> +        for index, obj in enumerate(self.content, 0):
сократил object, но не сократил index. пон...

2024-04-11 18:56 UTC, Ke1thuzad commented on src/gui_elements.py
> +        for ind, obj in enumerate(self.content, 0):
тогда уж i. 0 в enumerate писать необязательно.

2024-04-11 18:56 UTC, Ke1thuzad commented on src/gui_elements.py
> +        for index, obj in enumerate(self.content, 0):
0 в enumerate писать необязательно.

2024-04-12 10:58 UTC, Ke1thuzad approved these changes
fine

2024-04-12 10:59 UTC, merged