feature(RlAlg): added version-v1 RlAlg
Ecodrin/RLReversi pull request #18
Opened 2024-04-20 11:15 UTC by Ecodrin

2024-04-23 13:46 UTC, Ke1thuzad requested changes
Коммиты названы ужасно. -100 социального рейтинга, -кошка жена и миска рис.

2024-04-23 13:46 UTC, Ke1thuzad commented on env/tictactoe_gym/tictactoe_gym.py
> +        self.count_cell = pieces
лучше size. И в селф, и во входных данных.

2024-04-23 13:46 UTC, Ke1thuzad commented on env/tictactoe_gym/tictactoe_gym.py
> +        self.observation_space: spaces.Box = spaces.Box(low=-1, high=1, shape=(pieces, pieces), dtype=np.int8)
Зачем создавать переменную, которую не используешь?

2024-04-23 13:46 UTC, Ke1thuzad commented on env/tictactoe_gym/tictactoe_gym.py
> +        # Умный ход ботяры(глубина выбирается по тому, что вам нужно)
Если глубина выбирается пользователем, то сделай переменную просто.

2024-04-23 13:46 UTC, Ke1thuzad commented on env/tictactoe_gym/tictactoe_gym.py
> +        terminated = True if reward else False
Некорректная логика. При 0 тоже не завершается...

2024-04-23 13:46 UTC, Ke1thuzad commented on env/tictactoe_gym/tictactoe_gym.py
> +            self.display()
match case, exception handling, больше режимов.

2024-04-23 13:46 UTC, Ke1thuzad commented on env/tictactoe_gym/tictactoe_gym.py
> +            print()
Функции отображения не должны быть встроены в класс окружения

2024-04-23 13:46 UTC, Ke1thuzad commented on env/tictactoe_gym/tictactoe_gym.py
> +class ActionSpace(spaces.Space[np.ndarray]):
Название ни о чем не говорит. Если создаешь кастомный спейс, то нужно хотя бы название говорящее сделать.

2024-04-23 13:46 UTC, Ke1thuzad commented on env/tictactoe_gym/tictactoe_gym.py
> +class ActionSpace(spaces.Space[np.ndarray]):
и зачем здесь квадратные скобки?

2024-04-23 13:46 UTC, Ke1thuzad commented on main.py
Спасибо за этот файл для тестов, который мог бы отправиться в мейн брэнч.

2024-04-24 10:03 UTC, Ke1thuzad requested changes

2024-04-24 10:03 UTC, Ke1thuzad commented on env/tictactoe_gym/tictactoe_gym.py
> +        self.depht = depht
Глубина пишется не так...

2024-04-24 10:03 UTC, Ke1thuzad commented on env/tictactoe_gym/tictactoe_gym.py
> +        self.observation_space = gymnasium.spaces.Box(low=-1, high=1, shape=(1, self.size ** 2), dtype=np.int8)
почему у тебя двумерный массив здесь?

2024-04-24 10:03 UTC, Ke1thuzad commented on env/tictactoe_gym/tictactoe_gym.py
> +class ActionSpaceLegalMoves(spaces.Space):
Гениальное название.
```suggestion
class MoveSpace(spaces.Space):
```

2024-04-24 10:03 UTC, Ke1thuzad commented on env/tictactoe_gym/tictactoe_gym.py
> +                raise TypeError(f'mode {mode} not supported')
```suggestion
                raise TypeError(f'Mode "{mode}" is not supported.')
```

2024-04-24 10:03 UTC, Ke1thuzad commented on env/tictactoe_gym/tictactoe_gym.py
> +            return self.manager.board.board, reward, True, False, {'step': action, 'win': False, 'reward': reward}
Зачем тебе тогда observation space, если ты возвращаешь доску просто?

2024-04-24 10:03 UTC, Ke1thuzad commented on env/tictactoe_gym/tictactoe_gym.py
> +            print(f'{board[i * int(len(board) ** 0.5) + j]: >2} ', end='')
Каждый квадратный корень стоит 20 долларов...

2024-04-29 11:01 UTC, Ke1thuzad requested changes

2024-04-29 11:01 UTC, Ke1thuzad commented on env/tictactoe_gym/tictactoe_gym.py
>              print(f'{board[i * int(len(board) ** 0.5) + j]: >2} ', end='')
Зачем?

2024-05-01 14:33 UTC, anxiousss approved these changes
lgtm

2024-05-22 09:05 UTC, Ke1thuzad approved these changes

2024-05-22 09:05 UTC, merged