Feature/g UI/tic tac toe
Ecodrin/RLReversi pull request #19
Opened 2024-05-01 17:30 UTC by PinkCROCKS

2024-05-01 18:13 UTC, Ecodrin approved these changes
меняй архитектуру

2024-05-01 18:13 UTC, Ecodrin commented on src/gui.py
> +from typing import Callable, Any
https://peps.python.org/pep-0008/#imports

2024-05-01 18:13 UTC, Ecodrin commented on src/gui.py
> +        classic_text = StylizedText(hitbox, inner_text)
Классик текст? Почему классик? Как он относиться к кнопке? почему именно стандартные? Зачем ты тогда получаешь в функции  стиль и цвет и шрифт текста, если его не применяешь? Потом в назывании надо добавить если это какая то упрощенная кнопка функции

2024-05-01 18:13 UTC, Ecodrin commented on src/gui.py
> +        :param *args (arguments for callback function):
зачем звездочка

2024-05-01 18:13 UTC, Ecodrin commented on src/gui.py
> +        :return:
хаха это че

2024-05-01 18:13 UTC, Ecodrin commented on src/gui.py
> +    def create_image(self, name: str, file_with_image: str, coords_of_image: tuple) -> None:
typehints

2024-05-01 18:13 UTC, Ecodrin commented on src/gui.py
> +    def page_render(self) -> None:
комменты

2024-05-01 18:13 UTC, Ecodrin commented on src/gui.py
> +    def render_button(self, button_to_render: Button) -> None:
эмммм....зачем отдельная функция

2024-05-01 18:13 UTC, Ecodrin commented on src/gui.py
> +    def render_image(self, name_image_to_render: str) -> None:
typehints

2024-05-01 18:13 UTC, Ecodrin commented on src/gui.py
> +            for name in self.objects_on_the_screen:
если это словарь и тебе нужны только значения, то можно идти сразу по значениям. Вроде .values(не уверен)

2024-05-01 18:13 UTC, Ecodrin commented on src/gui.py
> +class ClassicGamePage():
скобки зачем

2024-05-01 18:13 UTC, Ecodrin commented on src/gui.py
> +    def create_home_page(self) -> None:
3 кнопки использующиеся в одном блоке - переделывай под GroupClassButton

2024-05-01 18:13 UTC, Ecodrin commented on src/gui.py
> +        self.create_button("Back", self.open_home_page, hitbox=pygame.Rect((65, 474, 130, 60)),
3 кнопки использующиеся в одном блоке - переделывай под GroupClassButton

2024-05-01 18:13 UTC, Ecodrin commented on src/gui.py
> +    def create_button(self, name_of_object: str, function_on_click: Callable, *args,
то же самое что и сверху и мне не нравится что полностью одинаковые функции в разных классах, переделывай, мб создать какую-то общую страницу где будут самые стандартные функции и наследовать этот класс.
?? еще и докстринги потерял

2024-05-01 18:13 UTC, Ecodrin commented on src/gui.py
> +    def create_visual_board(self):
комменты

2024-05-01 18:13 UTC, Ecodrin commented on src/gui.py
> +                    self.create_button(str(number_of_button), self.number_printer, number_of_button, hitbox=hitbox,
тебе сказали, для клеток создать специальный "облегченный " класс кнопок

2024-05-01 18:13 UTC, Ecodrin commented on src/gui.py
> +    def classic_game_processes(self) -> None:
комменты

2024-05-01 18:13 UTC, Ecodrin commented on src/gui.py
> +    def render_button(self, button_to_render: Button) -> None:
опять та же самая функция

2024-05-01 18:13 UTC, Ecodrin commented on src/gui.py
> +    def make_move(self, number: int = -1, crosses_player: int = 1, zeros_player=1) -> None:
docstrings

2024-05-01 18:13 UTC, Ecodrin commented on src/gui.py
> +    def crosses_move(self, number):
комменты typehints, docstring

2024-05-01 18:13 UTC, Ecodrin commented on src/gui.py
> +    def zeros_move(self, number):
чек выше

2024-05-01 18:13 UTC, Ecodrin commented on src/gui.py
> +    def is_game_continue(self):
это можно в одну строку уместить

2024-05-01 18:13 UTC, Ecodrin commented on src/gui.py
> +    def move_back(self) -> None:
комменты, докстринги

2024-05-01 18:13 UTC, Ecodrin commented on src/gui.py
> +            text = ['Ничья', "Крестики", "Нолики"]
зачем переменная

2024-05-01 18:13 UTC, Ecodrin commented on src/gui.py
> +            last_cell = self.visual_board[last_move]
комменты

2024-05-01 18:13 UTC, Ecodrin commented on src/gui.py
> +    def restart_game(self) -> None:
докстринги

2024-05-01 18:13 UTC, Ecodrin commented on src/gui.py
> +            for Cell in self.visual_board:
че, какие Cell это класс, ты че

2024-05-01 18:13 UTC, Ecodrin commented on src/gui.py
> +    def open_home_page(self) -> None:
докстринги

2024-05-01 18:13 UTC, Ecodrin commented on src/gui.py
> +    def number_printer(self, *args):
докстринги

2024-05-01 18:13 UTC, Ecodrin commented on src/gui.py
> +    def create_classic_game_page(self) -> None:
спорный момент - что такое класс гейм

2024-05-01 18:13 UTC, Ecodrin commented on src/gui.py
> +    def create_button(self, name_of_object: str, function_on_click: Callable, *args, hitbox: pygame.Rect = pygame.Rect((165, 300, 270, 60)),
докстринги

2024-05-01 18:13 UTC, Ecodrin commented on src/gui.py
> +        self.Neiro = Adversary(self.logic)
аахах ахахахаххаха

2024-05-01 18:13 UTC, Ecodrin commented on src/gui.py
> +        self.AI = Adversary(self.logic)
поменяй

2024-05-01 18:13 UTC, Ecodrin commented on src/gui.py
> +                c = self.crosses_player
переменные нормально назови

2024-05-01 18:13 UTC, Ecodrin commented on src/gui.py
> +    def classic_game_render(self) -> None:
докстринги

2024-05-01 18:23 UTC, Ecodrin requested changes
меняй архитектуру

2024-05-01 18:23 UTC, PinkCROCKS commented on src/gui.py
> +    def create_image(self, name: str, file_with_image: str, coords_of_image: tuple) -> None:
docstrings

2024-05-01 19:03 UTC, Ecodrin commented on src/gui.py
> +        self.AI = Adversary(self.logic)
очевидно

2024-05-01 19:22 UTC, anxiousss requested changes
Сначала делать, потом думать.

2024-05-01 19:22 UTC, anxiousss commented on src/gui.py
> +                z = self.zeros_player
?????????????????????

2024-05-01 19:22 UTC, anxiousss commented on src/gui.py
> +                z = self.zeros_player
нейминг переменных

2024-05-01 19:22 UTC, anxiousss commented on src/gui.py
> +                hitbox = pygame.Rect(112 + x * 131, 40 + y * 131, 122, 122)
Неочевидная логика. Нужен коммент

2024-05-01 19:22 UTC, anxiousss commented on src/gui.py
> +    def create_image(self, name: str, file_with_image: str, coords_of_image: tuple) -> None:
file_with_image должен быть os.PathLike

2024-05-01 19:22 UTC, anxiousss commented on src/gui.py
> +    def create_button(self, name_of_object: str, function_on_click: Callable, *args, hitbox: pygame.Rect = pygame.Rect((165, 300, 270, 60)),
Переделывай под другой класс

2024-05-01 19:22 UTC, anxiousss commented on src/gui.py
> +            elif event.type == pygame.KEYDOWN:
Не нужен if

2024-05-01 19:22 UTC, anxiousss commented on src/gui.py
> +            elif event.type == pygame.KEYDOWN:
(Замени условие)

2024-05-01 19:22 UTC, anxiousss commented on src/gui.py
> +        self.create_classic_game_page()
Type hints

2024-05-01 19:22 UTC, anxiousss commented on src/gui.py
> +                         (97, 296), (509, 296), 6)  # нижняя
Пропиши зависимость этих магических чисел с комментариями

2024-05-01 19:22 UTC, anxiousss commented on src/gui.py
> +            elif event.type == pygame.KEYDOWN:
бесполезный if

2024-05-01 19:22 UTC, anxiousss commented on src/gui.py
> +                Cell.onClick = self.number_printer
Слишком большая вложенность

2024-05-01 19:22 UTC, anxiousss commented on src/gui.py
> +                Cell.onClick = self.number_printer
Переименуй переменную в цикле.

2024-05-01 19:22 UTC, anxiousss commented on src/gui.py
> +            self.moves.remove(last_move)
type hints

2024-05-01 19:22 UTC, anxiousss commented on src/gui.py
> +                Cell.onClick = self.make_move
Нельзя так называть переменные.

2024-05-01 19:22 UTC, anxiousss commented on src/gui.py
> +    def number_printer(self, *args):
Название функции кринж.

2024-05-12 12:06 UTC, PinkCROCKS commented on src/gui.py
> +            elif event.type == pygame.KEYDOWN:
нельзя заменить, так как не у всех объектов типа event.type есть key

2024-05-12 12:08 UTC, PinkCROCKS commented on src/gui.py
> +        self.Neiro = Adversary(self.logic)
мощщный коммент, а главное невероятно понятный

2024-05-12 12:39 UTC, PinkCROCKS commented on src/gui.py
> +            text = ['Ничья', "Крестики", "Нолики"]
Какая переменная?

2024-05-12 22:00 UTC, Ecodrin requested changes
GG

2024-05-12 22:00 UTC, Ecodrin commented on src/constants.py
> +START_IMAGE_PATH = 'Start Desk.png'
Путь не строкой а os.PathLike(что мы раньше говорили)

2024-05-12 22:00 UTC, Ecodrin commented on src/constants.py
> +import pathlib
https://peps.python.org/pep-0008/#imports

2024-05-12 22:00 UTC, Ecodrin commented on src/constants.py
> +START_IMAGE_PATH = 'Start Desk.png'
снизу сделал, а тут

2024-05-12 22:00 UTC, Ecodrin commented on src/constants.py
> +BUTTON_DEFAULT_FONT_STYLE = 0
сделать константы для стилей

2024-05-12 22:00 UTC, Ecodrin commented on src/gui.py
> +import pygame
https://peps.python.org/pep-0008/#imports

2024-05-12 22:00 UTC, Ecodrin commented on src/gui.py
> +    def __init__(self,  screen: pygame.display, title: str = 'Tic-Tac-Toe', depth: int = 8, crosses_player: str = 'Игрок', zeros_player: str = "Комп") -> None:
вместо строки сделать ОТДЕЛЬНУЮ константу(0, 1,2)

2024-05-12 22:00 UTC, Ecodrin commented on src/gui.py
> +        players = {'Игрок': 0, "Комп": 1, 'Нейронка': 2}
Убрать словарь, кроме этого разные кавычки(в проекте все кавычки одинарные)

2024-05-12 22:00 UTC, Ecodrin commented on src/gui.py
> +        button = Button(function_on_click, *args, hitbox=hitbox, inner_text=text,
мы же поговорили в прошлый раз. Переделай под класс артемия

2024-05-12 22:00 UTC, Ecodrin commented on src/gui.py
> +        buttons.append(self.create_button(self.open_game_page,
GroupObjectClass и так имеет массив внутри, добавляй через функцию класса

2024-05-12 22:00 UTC, Ecodrin commented on src/gui.py
> +    def create_image(self, file_with_image: str) -> None:
os.PathLike(nice название, может image_path(P.S. Diman))

2024-05-12 22:00 UTC, Ecodrin commented on src/gui.py
> +        :param coords_of_image: координаты изображения
уууууу

2024-05-12 22:00 UTC, Ecodrin commented on src/gui.py
> +        :return:
None?

2024-05-12 22:00 UTC, Ecodrin commented on src/gui.py
> +                self.running = 0
мы не в Си(есть тип данных bool)

2024-05-12 22:00 UTC, Ecodrin commented on src/gui_elements.py
> +                 background_texture: pygame.color.Color | os.PathLike = pygame.color.Color(105, 103, 209), maksimum_value: int = 15):
![kadry-iz-filmov-i-serialov-kotorye-prevratilis-v-etalonnye-memy-2](https://github.com/Ecodrin/RLTicTacToe/assets/142536645/48a74b7a-e44e-489c-bb09-19ed479af769)

2024-05-12 22:00 UTC, Ecodrin commented on src/gui_elements.py
> +            if self.active:
![lyudi-eto-zerkala](https://github.com/Ecodrin/RLTicTacToe/assets/142536645/d1d439e4-c3da-4b3b-9b4a-54c33a87e051)
аххаха

2024-05-12 22:00 UTC, Ecodrin commented on src/gui_elements.py
> +            if self.active:
if много, переделай

2024-05-13 08:10 UTC, PinkCROCKS commented on src/gui.py
> +    def create_button(self, name_of_object: str, function_on_click: Callable, *args, hitbox: pygame.Rect = pygame.Rect((165, 300, 270, 60)),
кого переделывать под какой класс 1 функцию?

2024-05-13 08:35 UTC, PinkCROCKS commented on src/gui.py
> +    def create_image(self, file_with_image: str) -> None:
а какая разница блять

2024-05-13 16:08 UTC, anxiousss requested changes
Что опять работать, вам меня не жалко?

2024-05-13 16:08 UTC, anxiousss commented on src/gui.py
> +from constants import *
через * не делай импорт, пиши везде constansts

2024-05-13 16:08 UTC, anxiousss commented on src/gui.py
> +        classic_game_page = GamePage(
Переставь местами классы, чтобы GamePage был выше.

2024-05-13 16:08 UTC, anxiousss commented on src/gui.py
> +        return button
Лишняя функция.

2024-05-13 16:08 UTC, anxiousss commented on src/gui.py
> +    def create_user_size_button(self) -> None:
названии функции кринж.

2024-05-13 16:08 UTC, anxiousss commented on src/gui.py
> +        # win_text = NumberField(pygame.Rect(442, 680, 100, 90), 'win')
закомментированный код не должен присутствовать.

2024-05-13 16:08 UTC, anxiousss commented on src/gui.py
> +
сделай без if. Моя функция поддерживает и картинки и Rect.

2024-05-13 16:08 UTC, anxiousss commented on src/gui.py
> +        print(size)
Зачем?

2024-05-13 16:08 UTC, anxiousss commented on src/gui.py
> +        for i in self.rendered_pages:
i в этом цикле не обозначает индекс. (cringe)

2024-05-13 16:08 UTC, anxiousss commented on src/gui.py
> +        index = -1
Неясно, индекс чего?

2024-05-13 16:08 UTC, anxiousss commented on src/gui.py
> +        if size_field.correct_text and win_field.correct_text and int(win_field.text.content) <= int(size_field.text.content):
Класс NumberField надо бы поставить выше.

2024-05-13 16:08 UTC, anxiousss commented on src/gui.py
> +        return button
Та же претензия. Бесполезная функция.

2024-05-13 16:08 UTC, anxiousss commented on src/gui.py
> +        Создаёт кнопки для рестарта игры, взятие хода назад, и возвращения на главную страницу
Взятие хода назад?????

2024-05-13 16:08 UTC, anxiousss commented on src/gui.py
> +        self.objects_on_the_screen['groupOfButtons'] = group_of_buttons
Вторая повторяющийся функция????

2024-05-13 16:08 UTC, anxiousss commented on src/gui.py
> +        amount_of_sticks = self.size - 1
лучше n_sticks

2024-05-13 16:08 UTC, anxiousss commented on src/gui.py
> +        size_of_cell = (710 - amount_of_sticks * 20 - 10) // self.size
Магические числа должны быть убраны.

2024-05-13 16:08 UTC, anxiousss commented on src/gui.py
> +                                     y * (20 + size_of_cell), size_of_cell, size_of_cell)
Магические числа должны быть убраны. (2)

2024-05-13 16:08 UTC, anxiousss commented on src/gui.py
> +                    cell = ClicableCell(hitbox, self.number_printer, default_texture=pygame.color.Color(
Более понятное название переменной нужно.

2024-05-13 16:08 UTC, anxiousss commented on src/gui.py
> +                i}"] = pygame.Rect(coords_horizontal)
Все те же претензии, что и к предыдущей функции.

2024-05-13 16:08 UTC, anxiousss commented on src/gui.py
> +                pygame.draw.rect(self.home_page.screen, (133, 116, 115),
Магические числа (3)

2024-05-13 16:08 UTC, anxiousss commented on src/gui.py
> +        if (self.crosses_player == 1 == self.zeros_player) and self.is_game_continue():
зачем скобки?

2024-05-13 16:08 UTC, anxiousss commented on src/gui.py
> +                сell.onClick = self.number_printer
функцию пораньше надо бы поставить

2024-05-13 16:08 UTC, anxiousss commented on src/gui.py
> +        elif (len(self.moves) % 2 != 0):  # Если ход ноликов
зачем скобки в if?

2024-05-13 16:08 UTC, anxiousss commented on src/gui.py
> +                    self.zeros_move(computers_turn)
число в serch_root должно определяться полем.

2024-05-13 16:08 UTC, anxiousss commented on src/gui.py
> +                    computers_turn = self.computer.search_root(3)
same like the prev

2024-05-13 16:08 UTC, anxiousss commented on src/gui.py
> +            self.visual_board[number].onClick = self.number_printer
обе функции поставить до make_move.

2024-05-13 16:08 UTC, anxiousss commented on src/gui.py
> +            text = ['Ничья', "Крестики", "Нолики"]
useless variable text.

2024-05-13 16:08 UTC, anxiousss commented on src/gui.py
> +            self.moves.remove(last_move)
1. скобки в условиях 2. оба условия выполняет одинаковые операции -> зачем второе условие????

2024-05-13 16:08 UTC, anxiousss commented on src/gui.py
> +    def number_printer(self, *args) -> None:
название все ещё бомба

2024-05-13 16:08 UTC, anxiousss commented on src/gui_elements.py
> +from constants import *
импорт через * - NO NO NO

2024-05-13 16:08 UTC, anxiousss commented on src/gui_elements.py
> +                     64, 64, 64),
числа в константы

2024-05-13 16:08 UTC, anxiousss commented on src/gui_elements.py
> +    def __init__(self, hitbox: pygame.Rect = pygame.Rect(300, 200, 200, 50), background_text: StylizedText | str = 'ty',
str = 'ty' ВОООООО

2024-05-13 16:08 UTC, anxiousss commented on src/gui_elements.py
> +                 background_texture: pygame.color.Color | os.PathLike = pygame.color.Color(105, 103, 209), maksimum_value: int = 15):
константы и переменные по-русски не называем

2024-05-13 16:26 UTC, anxiousss commented on src/gui.py
> +        elif (len(self.moves) % 2 != 0):  # Если ход ноликов
можно просто оставить len(self.moves) % 2

2024-05-13 16:28 UTC, anxiousss commented on src/gui_elements.py
> +                 background_texture: pygame.color.Color | os.PathLike = pygame.color.Color(105, 103, 209), maksimum_value: int = 15):
кста repr и str в каждый класс добавь

2024-05-13 20:58 UTC, anxiousss commented on src/gui.py
> +        size_of_cell = (710 - amount_of_sticks * 20 - 10) // self.size
(должен быть написан комментарий)

2024-05-13 20:58 UTC, anxiousss commented on src/gui.py
> +                    cell = ClicableCell(hitbox, self.number_printer, default_texture=pygame.color.Color(
явно такое название не отражает суть

2024-05-13 20:59 UTC, anxiousss commented on src/gui.py
> +                                     y * (20 + size_of_cell), size_of_cell, size_of_cell)
(должен быть написан комментарий)

2024-05-13 20:59 UTC, anxiousss commented on src/gui.py
> +                pygame.draw.rect(self.home_page.screen, (133, 116, 115),
(должен быть написан комментарий)

2024-05-13 21:01 UTC, anxiousss commented on src/gui.py
> +            text = ['Ничья', "Крестики", "Нолики"]
если это на следующий таск, то зачем это писать в этом??????

2024-05-15 10:50 UTC, Ecodrin requested changes
Переделывай и ты забыл .png сложить в отдельную папку, ще делай названия файлов с пробелом

2024-05-15 10:50 UTC, Ecodrin commented on src/constants.py
> +import pathlib
Imports should be grouped in the following order:

Standard library imports.
Related third party imports.
Local application/library specific imports.

2024-05-15 10:50 UTC, Ecodrin commented on src/gui.py
> +import os
Imports should be grouped in the following order:

Standard library imports.
Related third party imports.
Local application/library specific imports.

2024-05-15 10:50 UTC, Ecodrin commented on src/gui_elements.py
> +from pygame.locals import Rect
Imports should be grouped in the following order:

Standard library imports.
Related third party imports.
Local application/library specific imports.

2024-05-15 10:50 UTC, Ecodrin commented on src/gui_elements.py
> +                     160, 160, 160),
константы в отдельный файл, например WHITE = pygame.color.Color(...)

2024-05-15 10:50 UTC, Ecodrin commented on src/gui_elements.py
> +                     160, 160, 160),
это касается всех файлов

2024-05-15 10:50 UTC, Ecodrin commented on src/gui_elements.py
> +        self.click_field: bool = False
давай лучше переменные булевского типа: self.is_correct_text(остальное аналогично)

2024-05-15 10:50 UTC, Ecodrin commented on src/gui.py
> +        Функция, отвечающая за визуализацию Страниц игры.
"страниц" с маленькой буквы

2024-05-15 10:50 UTC, Ecodrin commented on src/gui.py
> +        Создаёт Страницу с игрой с необходимыми данными и добавляет её в массив созданных страниц
я русский

2024-05-15 10:50 UTC, Ecodrin commented on src/gui.py
> +        :param pieces_to_win: Колличество в ряд для победы
я русский

2024-05-15 10:50 UTC, Ecodrin commented on src/gui.py
> +        :param pieces_to_win: Колличество в ряд для победы
я русский

2024-05-15 10:50 UTC, Ecodrin commented on src/gui.py
> +        Создание группы кнопок на начальной странице  и добавление их в словарь со всеми объектами
лишний пробел и поставь точку

2024-05-15 10:50 UTC, Ecodrin commented on src/gui.py
> +class HomePage:
забыл написать str rerp

2024-05-15 10:50 UTC, Ecodrin commented on src/gui.py
> +class HomePage:
забыл написать str rerp

2024-05-15 10:50 UTC, Ecodrin commented on src/gui.py
> +            self.pieceses_to_win: int = self.size
хаха, меняй название PIECES

2024-05-15 10:50 UTC, Ecodrin commented on src/gui.py
> +                pygame.draw.rect(self.home_page.screen, (133, 116, 115),
магические числа так и не убрали

2024-05-15 10:51 UTC, Ecodrin commented on src/gui.py
> +class HomePage:
второй класс - тоже

2024-05-15 14:20 UTC, Ke1thuzad requested changes
Прям супер повторяющиеся ошибки рядом друг с другом не стал писать, пересмотри еще раз свой код и исправь повторяшки

2024-05-15 14:20 UTC, Ke1thuzad commented on Frame 4.png
Все картинки в свою папочку.

2024-05-15 14:20 UTC, Ke1thuzad commented on src/board.py
> +    def __init__(self, hitbox: pygame.Rect, onClick: Callable, *args) -> None:
Зачем? Это одно и то же, пусть останется просто Rect

2024-05-15 14:20 UTC, Ke1thuzad commented on src/constants.py
> +import pathlib
Между каждой группой импортов должны быть разделяющие пробелы.

2024-05-15 14:20 UTC, Ke1thuzad commented on src/constants.py
> +CROSSES_TEXTURE = pathlib.Path("Union.png")
Почему двойные?

2024-05-15 14:20 UTC, Ke1thuzad commented on src/constants.py
> +BUTTON_DEFAULT_FONT_STYLE = 0
Где?

2024-05-15 14:20 UTC, Ke1thuzad commented on src/constants.py
> +BUTTON_FOUR_HITBOX = pygame.Rect(242, 380, 400, 90)
Почему здесь через 4 инта, а ниже через tuple?

2024-05-15 14:20 UTC, Ke1thuzad commented on src/constants.py
> +BUTTON_GENERATE_HITBOX = pygame.Rect((242, 770, 400, 90))
Здесь

2024-05-15 14:20 UTC, Ke1thuzad commented on src/constants.py
> +BUTTON_GENERATE_CLICK_TEXTURE = pygame.color.Color((103, 171, 209))
То же самое, что и 23-26

2024-05-15 14:20 UTC, Ke1thuzad commented on src/constants.py
> +BUTTON_BACK_CLICK_TEXTURE = pygame.color.Color((103, 171, 209))
?

2024-05-15 14:20 UTC, Ke1thuzad commented on src/constants.py
> +BUTTON_BACK_CONTENT = 'Back'
27 строка текст на русском, здесь - на английском. Why?

2024-05-15 14:20 UTC, Ke1thuzad commented on src/constants.py
> +NUMBERFIELD_FOR_SIZE_CONTENT = 'size'
Теперь не только на английском, но и с маленькой буквы?

2024-05-15 14:20 UTC, Ke1thuzad commented on src/constants.py
> +NUMBERFIELD_FOR_SIZE_FONT_STYLE = 'bold'
Не только без константы, но и текстом теперь

2024-05-15 14:20 UTC, Ke1thuzad commented on src/constants.py
> +STICKS_COLOR = pygame.color.Color(133, 116, 115)
Что значит "цвет палок"?

2024-05-15 14:20 UTC, Ke1thuzad commented on src/gui_elements.py
>  from typing import Callable, Any
Разные группы импортов. (пробел?)

2024-05-15 14:20 UTC, Ke1thuzad commented on src/gui_elements.py
> -
пробел?

2024-05-15 14:20 UTC, Ke1thuzad commented on src/gui_elements.py
> +                     255, 255, 255),
Ужасная сноска, верни обратно)

2024-05-15 14:20 UTC, Ke1thuzad commented on src/gui_elements.py
> +                                pygame.Rect]] = self.__create_text()
Сноска тоже не ахти.

2024-05-15 14:20 UTC, Ke1thuzad commented on src/gui_elements.py
> +        ), self.__is_italic(), self.__is_underline()
?????????????????????????
Что за ужас...
Если на новую строку переносишь, то переноси все на свою и с отступом. Так:
![image](https://github.com/Ecodrin/RLTicTacToe/assets/66142897/feaac8dc-f50b-4584-bbb1-7739b6088ae8)

2024-05-15 14:20 UTC, Ke1thuzad commented on src/gui_elements.py
> +        ), self.__is_italic(), self.__is_underline()
Или уже раздели на 3 переменные отдельные, так читабельнее будет.

2024-05-15 14:20 UTC, Ke1thuzad commented on src/gui_elements.py
> +        y_offset = self.position[1] + \
Создай еще одну переменную, куда результат вычисления этой большой скобки запихнешь.

2024-05-15 14:20 UTC, Ke1thuzad commented on src/gui_elements.py
> +                      2, y_offset + font.size(text_line)[1] // 2)
+2 переменные

2024-05-15 14:20 UTC, Ke1thuzad commented on src/gui_elements.py
> +class ClicableCell(Clickable):
Куда k пропала?

2024-05-15 14:20 UTC, Ke1thuzad commented on src/gui_elements.py
> +                 hover_texture: pygame.color.Color | os.PathLike = pygame.color.Color(160, 160, 160)) -> None:
Научись разделять пжпжпж.
Перенес 1 параметр - перенеси все на свои строчки.

2024-05-15 14:20 UTC, Ke1thuzad commented on src/gui_elements.py
> +    def render(self, screen: pygame.surface) -> None:
Здесь нужен класс (с большой буквы Surface надо короче)

2024-05-15 14:20 UTC, Ke1thuzad commented on src/gui_elements.py
> +                self.hover_texture}"
Мне хочется плакац

2024-05-15 14:20 UTC, Ke1thuzad commented on src/gui_elements.py
> +                self.inner_text.position, value)
Why snoska

2024-05-15 14:20 UTC, Ke1thuzad commented on src/gui_elements.py
> +                self.border_radius})"
устал

2024-05-15 14:20 UTC, Ke1thuzad commented on src/gui_elements.py
> +                element=item.hitbox, relative_to=self.__position, mode=axis)
эх

2024-05-15 14:20 UTC, Ke1thuzad commented on src/gui_elements.py
> +                element=item.hitbox, relative_to=self.__position, mode=axis)
![image](https://github.com/Ecodrin/RLTicTacToe/assets/66142897/b0b8fc47-a8e1-4529-b596-a74062f5feed)
должно быть так

2024-05-15 14:20 UTC, Ke1thuzad commented on src/gui_elements.py
> +                 background_texture: pygame.color.Color | os.PathLike = pygame.color.Color(105, 103, 209), max_value: int = 15):
эх

2024-05-15 14:20 UTC, Ke1thuzad commented on src/gui_elements.py
> +        :param background_text: текст на блоке по-умолчанию
```suggestion
        :param background_text: текст на блоке по умолчанию
```

2024-05-15 14:20 UTC, Ke1thuzad commented on src/gui_elements.py
> +                self.hitbox, background_text)
эх

2024-05-15 14:20 UTC, Ke1thuzad commented on src/gui_elements.py
> +                self.hitbox, background_text)
зачем здесь вообще было переносить?

2024-05-15 14:20 UTC, Ke1thuzad commented on src/gui_elements.py
> +        self.is_click_field: bool = False
не понимаю смысла этой переменной. для чего она?
"клик поле ли"?
выбрано ли поле? Тогда "is_selected" или что-то в этом роде

2024-05-15 14:20 UTC, Ke1thuzad commented on src/gui_elements.py
> +    def render(self, screen: pygame.display):
тайпхинт тоже не является классом и не будет помогать ничем

2024-05-15 14:20 UTC, Ke1thuzad commented on src/gui_elements.py
> +                img = self._image_cache
если это так часто используется, то можно, наверное, вынести это в отдельную функцию какую-нибудь?

2024-05-15 14:20 UTC, Ke1thuzad commented on src/gui_elements.py
> +                    self.text.content = self.text.content[:-1]
Если здесь 2 общих параметра и только 1 отличается, то почему бы не сократить и вынести в отдельный иф?

2024-05-15 14:20 UTC, Ke1thuzad commented on src/gui_elements.py
> +                    self.text.content = self.text.content[:-1]
Каво?

2024-05-15 14:20 UTC, Ke1thuzad commented on src/gui_elements.py
> +                        self.text.content += event.unicode
внутри ифов одинаковая строчка. Тоже можно сократить

2024-05-15 14:20 UTC, Ke1thuzad commented on src/gui_elements.py
> +                        self.text.content += event.unicode
Порядок условий неоптимизированный. Насколько чаще юзер будет жать на бэкспейс, а не печатать?

2024-05-15 14:20 UTC, Ke1thuzad commented on src/manager.py
> +from board import Board
src.board правильно было

2024-05-15 14:20 UTC, Ke1thuzad commented on src/manager.py
>  from abc import ABC, abstractmethod
from и import тоже отделяется пробелами. Разные группы

2024-05-15 14:20 UTC, Ke1thuzad commented on src/tictactoe.py
> +from manager import GameManager
src где

2024-05-15 14:20 UTC, Ke1thuzad commented on src/gui_elements.py
> +        return f"NumberField with background_text '{self.background_text}' and hitbox {self.hitbox}"
двойные кавычки

2024-05-15 14:20 UTC, Ke1thuzad commented on src/gui_elements.py
>          return f'"Text {self._content}, Size {self.font_size}, Colour {self.text_colour}'
двойные

2024-05-15 14:20 UTC, Ke1thuzad commented on src/gui_elements.py
> +                self.hover_texture}"
(+двойные)

2024-05-15 14:20 UTC, Ke1thuzad commented on src/gui_elements.py
> +                self.border_radius})"
(+двойные)

2024-05-15 14:20 UTC, Ke1thuzad commented on src/gui_elements.py
>          return f"Button with text '{self.inner_text}' and hitbox {self.hitbox}"
двойные

2024-05-15 14:29 UTC, anxiousss requested changes
![image](https://github.com/Ecodrin/RLTicTacToe/assets/145536203/58b691df-59c1-4a17-8b32-3d370158a026)

Бесконечные изменения.

2024-05-15 14:29 UTC, anxiousss commented on src/gui.py
> +from manager import Adversary
import не мешаем с from.

2024-05-15 14:29 UTC, anxiousss commented on src/gui.py
> +        self.objects_on_the_screen.append(pygame.image.load(image_path))
удали функцию, где она используется замени на одну строчку.

2024-05-15 14:29 UTC, anxiousss commented on src/gui.py
> +        generate_button = Button(self.user_game, size_block, win_block, hitbox=const.BUTTON_GENERATE_HITBOX,
В названии переменной не должно быть глагольных конструкций.

2024-05-15 14:29 UTC, anxiousss commented on src/gui.py
> +
переделай repr так, чтобы можно было создать объект с этими полями.

2024-05-15 14:29 UTC, anxiousss commented on src/gui.py
> +                    not_cell = ClicableCell(hitbox, self.print_number, default_texture=pygame.color.Color(  # 10 - размер палочки + 5 пикселей отступы между клеткой и панками
Комментарии уехали.

2024-05-15 14:29 UTC, anxiousss commented on src/gui.py
> +                    not_cell = ClicableCell(hitbox, self.print_number, default_texture=pygame.color.Color(  # 10 - размер палочки + 5 пикселей отступы между клеткой и панками
Переименуй переменную.

2024-05-15 14:29 UTC, anxiousss commented on src/gui.py
> +                               i + 10 * (i - 1), 20, 10, 710)
место комментариев просто бомба.

2024-05-15 14:29 UTC, anxiousss commented on src/gui.py
> +                    self.home_page.running = False
В одно условие.

2024-05-15 14:29 UTC, anxiousss commented on src/gui_elements.py
> +                 hover_texture: pygame.color.Color | os.PathLike = pygame.color.Color(160, 160, 160)) -> None:
Должно быть константы.

2024-05-15 14:29 UTC, anxiousss commented on src/gui_elements.py
> +                self._image_cache = img
Использование поля, которого нет в классе.

2024-05-15 14:29 UTC, anxiousss commented on src/gui_elements.py
> +        """
Должны быть константы.

2024-05-21 14:26 UTC, anxiousss requested changes
auto pep8 fix pls

2024-05-21 14:26 UTC, anxiousss commented on environment/tictactoe_gym/tictactoe_gym.py
> +            Board(size), pieces_to_win)
auto pep8 ruin

2024-05-21 14:26 UTC, anxiousss commented on environment/tictactoe_gym/tictactoe_gym.py
> +            3 ** (size ** 2))
auto pep8 ruin 2

2024-05-21 14:26 UTC, anxiousss commented on neiro.py
> +# agent.save('agent2_100k')
закомментированный код надо удалить.

2024-05-21 14:26 UTC, anxiousss commented on src/agent.py
> +            self.q_values[obs][action] + self.lr * temporal_difference
auto pep8 ruin 3

2024-05-21 14:26 UTC, anxiousss commented on src/agent.py
> +                           self.epsilon - self.epsilon_decay)
auto pep8 ruin 4

2024-05-21 14:26 UTC, anxiousss commented on src/agent.py
auto pep8 ruin 5

2024-05-21 14:26 UTC, anxiousss commented on src/gui.py
> +            pygame.image.load(const.START_IMAGE_PATH))
auto pep8 ruin 6

2024-05-21 14:26 UTC, anxiousss commented on src/gui.py
>                                  pieces_to_win=int(win_field.text.content))
auto pep8 ruin 7

2024-05-21 14:26 UTC, anxiousss commented on src/gui.py
> +                                 const.INNER_BOARDERS_COLOR, object)
auto pep8 ruin 8

2024-05-21 14:26 UTC, anxiousss commented on src/gui.py
> +                        self.logic.board.get_uid(), self.logic.find_legal_moves())[1]
auto pep8 ruin 9

2024-05-21 14:26 UTC, anxiousss commented on src/gui.py
> +                    self.zeros_move(computers_turn)
auto pep8 ruin 10

2024-05-22 09:33 UTC, Ecodrin approved these changes

2024-05-22 09:51 UTC, Ke1thuzad approved these changes

2024-05-22 10:08 UTC, merged