Vp 21 stylized text update
Ecodrin/RLReversi pull request #5
Opened 2024-03-26 18:52 UTC by anxiousss

2024-03-26 19:02 UTC, Ecodrin commented on src/stylized_text.py
> +    def __init__(self, content: str = 'Hello world', Rect: pygame.Rect = (), TextColour: tuple = (0, 0, 0),
не круто, что название Rect пересекается с функцией pygame

2024-03-26 20:21 UTC, Ke1thuzad requested changes
респект за понятные названия переменных

2024-03-26 20:21 UTC, Ke1thuzad commented on src/stylized_text.py
> +                 FontFamily: str = 'Arial', FontSize: int = 24, FontStyle: int = 0) -> None:
Названия с маленькой буквы пишем.

2024-03-26 20:21 UTC, Ke1thuzad commented on src/stylized_text.py
> +                 FontFamily: str = 'Arial', FontSize: int = 24, FontStyle: int = 0) -> None:
Ну и Rect переименовать в position какой-нибудь или rectangle просто.

2024-03-26 20:21 UTC, Ke1thuzad commented on src/stylized_text.py
> +        return self.FontSize % 10
Для побитовых операций используем маски.
Пример:
0b11 & 0b10 - проверка на курсив, где первое двоичное входное, а второе - маска.
(или x & 2 в десятичной)

2024-03-26 20:21 UTC, Ke1thuzad commented on src/stylized_text.py
> +        return self.FontSize / 10 % 10
Аналогично с предыдущим.
+ названия с маленькой буквы.

2024-03-26 20:21 UTC, Ke1thuzad commented on src/stylized_text.py
> +        return self.FontSize % 10
название

2024-03-26 20:21 UTC, Ke1thuzad commented on src/stylized_text.py
> +        font = pygame.font.SysFont(self.FontFamily, self.FontSize, bold=bold, italic=italic)
а хде подчеркивание?

2024-03-26 20:21 UTC, Ke1thuzad commented on src/stylized_text.py
> +    def __init__(self, content: str = 'Hello world', Rect: pygame.Rect = (), TextColour: tuple = (0, 0, 0),
colour должен использовать **пайгеймовский класс Color**

2024-03-26 20:21 UTC, Ke1thuzad commented on src/stylized_text.py
> +    def render(self, screen) -> None:
type hints ?

2024-03-26 20:21 UTC, Ke1thuzad commented on src/stylized_text.py
> +        return self.FontSize % 10
неправильная логика, почему _self.FontSize_ % 10 ??

2024-03-26 20:21 UTC, Ke1thuzad commented on src/stylized_text.py
> +        return self.FontSize / 10 % 10
аналогично про логику

2024-03-26 21:17 UTC, anxiousss commented on src/stylized_text.py
> +        font = pygame.font.SysFont(self.FontFamily, self.FontSize, bold=bold, italic=italic)
его нет в этом методе

2024-03-27 16:25 UTC, Ecodrin requested changes

2024-03-27 16:25 UTC, Ecodrin commented on src/stylized_text.py
> +        match mask:
хз как лучше, но выглядит трешово. МБб словарь лучше?

2024-03-27 16:25 UTC, Ecodrin commented on src/stylized_text.py
> +    def __styles_determinate(self):
type hints?

2024-03-27 16:28 UTC, Ecodrin requested changes

2024-03-27 16:28 UTC, Ecodrin commented on src/stylized_text.py
> +        match mask:
Подожди с этим до ревью Димы

2024-03-27 16:28 UTC, anxiousss commented on src/stylized_text.py
> +        match mask:
?

2024-03-27 16:28 UTC, anxiousss commented on src/stylized_text.py
> +    def __styles_determinate(self):
где

2024-03-27 16:42 UTC, Ecodrin commented on src/stylized_text.py
> +    def __styles_determinate(self):
Что возвращает функция?

2024-03-27 17:56 UTC, Ke1thuzad requested changes

2024-03-27 17:56 UTC, Ke1thuzad commented on src/stylized_text.py
> +        mask = self.font_style & 0b11
абсолютно убил весь смысл масок.
is_cursive = style & 0b10
is_bold = style & 0b01

2024-03-27 17:56 UTC, Ke1thuzad commented on src/stylized_text.py
> +    def __init__(self, content: str = 'Hello world', position: pygame.Rect = (), text_colour: pygame.color = (0, 0, 0),
content по дефолту **пустой**

2024-03-27 17:56 UTC, Ke1thuzad commented on src/stylized_text.py
> +        :param font_style: Стиль текста
добавь в пояснение как выбрать стиль текста (через маски и десятичные числа)

2024-03-27 17:56 UTC, Ke1thuzad commented on src/stylized_text.py
> +    def __styles_determinate(self) -> tuple:
тогда уж determine styles, но лучше бы что-нибудь попроще, менее умное)

2024-03-27 17:56 UTC, Ke1thuzad commented on src/stylized_text.py
> +        :param screen: разрешение экрана
не разрешение, а screen instance (только на русском)

2024-03-27 20:34 UTC, anxiousss commented on src/stylized_text.py
> +        :param screen: разрешение экрана
кринж чел

2024-03-27 20:34 UTC, anxiousss commented on src/stylized_text.py
> +        :param screen: разрешение экрана
`# Размеры экрана
screen_width = 800
screen_height = 600
screen = pygame.display.set_mode((screen_width, screen_height))`

2024-03-27 20:34 UTC, anxiousss commented on src/stylized_text.py
> +        :param screen: разрешение экрана
это типо не разрешение?

2024-03-27 20:45 UTC, Ke1thuzad commented on src/stylized_text.py
> +        :param screen: разрешение экрана
это объект окна
![image](https://github.com/Ecodrin/RLReversi/assets/66142897/ae2e1fc9-3347-405b-8a9a-2c1a2d5a96b1)

2024-03-27 21:31 UTC, anxiousss commented on src/stylized_text.py
> +        :param screen: разрешение экрана
fix

2024-03-28 07:51 UTC, Ke1thuzad approved these changes
lgtm

2024-03-28 07:54 UTC, Ecodrin approved these changes
bbbb...aaaa

2024-03-28 07:55 UTC, merged