Gui classes complete
Ecodrin/RLReversi pull request #7
Opened 2024-03-29 18:20 UTC by anxiousss

2024-03-29 20:55 UTC, Ke1thuzad requested changes

2024-03-29 20:55 UTC, Ke1thuzad commented on src/gui_elements.py
> +from typing import Union
Сначала идут питоновские библиотеки, потом сторонние, потом внутренние.

2024-03-29 20:55 UTC, Ke1thuzad commented on src/gui_elements.py
> +        self.position[2], self.position[3] = text_surface.get_width(), text_surface.get_height()
Наоборот, текст должен быть в рамках заданного прямоугольника ?!

2024-03-29 20:55 UTC, Ke1thuzad commented on src/gui_elements.py
> +                 click_texture: Union[tuple, str] = (0, 255, 0)) -> None:
Зачем импортировать лишнее, если специально добавили | для облегчения этой задачи? Тем более, в другом файле у нас | , так что лучше здесь тоже поменять для систематичности.

2024-03-29 20:55 UTC, Ke1thuzad commented on src/gui_elements.py
> +                 inner_text: StylizedText = '',
Ты создаешь дефолтное значение типа str, когда у тебя typehint типа StylizedText.

2024-03-29 20:55 UTC, Ke1thuzad commented on src/gui_elements.py
> +        collide = self.hitbox.collidepoint(point)
Т.к. это используется 2 раза, то можно в родительском классе прописать функцию проверки на коллизию, которая будет возвращать bool.

2024-03-29 20:55 UTC, Ke1thuzad commented on src/gui_elements.py
> +        collide = self.hitbox.collidepoint(point)
и здесь использовать через super

2024-03-29 20:55 UTC, Ke1thuzad commented on src/gui_elements.py
> +            self.inner_text.render(screen)
Зачем 2 раза прописывать одну строку (97, 102), если можно вынести из условия?

2024-03-29 20:55 UTC, Ke1thuzad commented on src/gui_elements.py
> +                f'{self.click_texture}, {self.onClick}, {self.args}, {self.hitbox}')
В репре всегда нужно указание на класс объекта, в данном случае Button(_data_), где data - параметры.

2024-03-29 20:55 UTC, Ke1thuzad commented on src/gui_elements.py
> +                f'{self.click_texture}, {self.onClick}, {self.args}, {self.hitbox}')
И hitbox является более читаемым объектом, чем функция onClick и более важным, чем текстуры и функция, поэтому он идет между текстом и текстурами (2 с начала).

2024-03-29 20:55 UTC, Ke1thuzad commented on src/gui_elements.py
> +        return f'{self.inner_text}, {self.default_texture}, {self.hover_texture}, {self.click_texture}'
Здесь позиция тоже важна.

2024-03-29 20:55 UTC, Ke1thuzad commented on src/gui_elements.py
> +        return f'{self.inner_text}, {self.default_texture}, {self.hover_texture}, {self.click_texture}'
И желательно добавить тоже кавычки для текста, т.к. в StylizedText они стоят. Нужно придерживаться одного стиля написания кода.

2024-03-29 20:55 UTC, Ke1thuzad commented on src/gui_elements.py
> +        else:
Что, если передам на вход в default_texture параметр вида bool/int/float?

2024-03-29 20:55 UTC, Ke1thuzad commented on src/gui_elements.py
> +                 click_texture: Union[tuple, str] = (0, 255, 0)) -> None:
Ну не самые лучшие дефолтные значения)
Обычная текстура должна быть белой, при наведении чуть-чуть более серая, при клике должна быть серая.

2024-03-29 20:55 UTC, Ke1thuzad commented on src/gui_elements.py
> +        :param font_style: Стиль текста. Задаётся битовой маской: 0b01 - жирный, 0b10 - курсив.
Слишком много текста, у тебя класс и так называется текст, тут некоторое можно убрать (кроме размера текста и т.п.)

2024-03-29 20:55 UTC, Ke1thuzad commented on src/gui_elements.py
> +    def hover_click(self, event: pygame.event) -> None:
Название функции непонятное, а комментариев нет...

2024-03-29 20:55 UTC, Ke1thuzad commented on src/gui_elements.py
> +    def hover_click(self, event: pygame.event) -> None:
Да и проверку на коллизии КАЖДЫЙ EVENT я бы не делал, код неоптимизированный то получается.

2024-03-29 22:31 UTC, Ke1thuzad requested changes
Возможно, еще что-то не заметил, но это основное

2024-03-29 22:31 UTC, Ke1thuzad commented on src/gui_elements.py
> +                 click_texture: tuple | str = (64, 64, 64)) -> None:
Желательно добавить еще поддержку pygame.Color (для hex-цветов #ffffff и т.д.)

2024-03-29 22:31 UTC, Ke1thuzad commented on src/gui_elements.py
> +                 inner_text: StylizedText,
Код сразу выдаст ошибку (вроде), позиционный параметр среди ключевых, задай стандартный текст просто без ничего. (default of StylizedText = "")

2024-03-29 22:31 UTC, Ke1thuzad commented on src/gui_elements.py
> +from сell import Clickable
https://peps.python.org/pep-0008/#imports

2024-03-29 22:31 UTC, Ke1thuzad commented on src/gui_elements.py
> +    def __init__(self, content: str = '', position: pygame.Rect = (), text_colour: tuple = (0, 0, 0),
Лучше тогда без дефолтного значения у позиции.

2024-03-29 22:31 UTC, Ke1thuzad commented on src/gui_elements.py
> +        :param screen: Разрешение выводимого окна
Не разрешение, а объект дисплея для обновления содержимого.
(Разрешение это tuple[int, int].)

2024-03-29 22:31 UTC, Ke1thuzad commented on src/gui_elements.py
> +        return (f'Button("{self.inner_text}", {self.hitbox},{self.default_texture}, {self.hover_texture},'
А в repr StylizedText без кавычек, тогда уж либо там добавь, либо здесь убери)
Желательно 1.

2024-03-29 22:31 UTC, Ke1thuzad commented on src/сell.py
>  import pygame
https://peps.python.org/pep-0008/#imports

2024-04-02 15:18 UTC, Ke1thuzad requested changes
Удачи.

2024-04-02 15:18 UTC, Ke1thuzad commented on src/gui_elements.py
> +        self.borders: pygame.Rect = borders
Костыль, границы должны передаваться через позицию.

2024-04-02 15:18 UTC, Ke1thuzad commented on src/gui_elements.py
> +            font.set_italic(italic == 2)
В отдельную внутреннюю функцию для создания шрифта.

2024-04-02 15:18 UTC, Ke1thuzad commented on src/gui_elements.py
> +            print(line)
print ???

2024-04-02 15:18 UTC, Ke1thuzad commented on src/gui_elements.py
> +            y_offset += self.font_size
Перенести разбиение текста на строки через font.size(word) (для оптимизации). 
В render _желательно_ оставить 2 строки.

2024-04-02 15:18 UTC, Ke1thuzad commented on src/gui_elements.py
> +                                                      y_offset + self.font_size // 2))
Слишком нагруженная строка.

2024-04-02 15:18 UTC, Ke1thuzad commented on src/gui_elements.py
> +            img = pygame.transform.scale(img, (self.hitbox[2], self.hitbox[3]))
В отдельную функцию. Render вызывается каждый кадр, не нужно нагружать код, т.к. каждая строчка важна.
Нужны только фундаментальные функции (blit, etc...)

2024-04-02 15:18 UTC, Ke1thuzad commented on src/gui_elements.py
> +            raise TypeError('Invalid texture type')
match?

2024-04-02 15:18 UTC, Ke1thuzad commented on src/gui_elements.py
> +        return f'"{self.inner_text}", {self.hitbox}, {self.default_texture}, {self.hover_texture}, {self.click_texture}'
Скобки?

2024-04-02 15:19 UTC, Ecodrin approved these changes
bbb

2024-04-03 18:11 UTC, Ecodrin approved these changes

2024-04-03 20:16 UTC, Ke1thuzad requested changes
Еще и коммит назвал очень плохо....

2024-04-03 20:16 UTC, Ke1thuzad commented on src/gui_elements.py
> +        surface_lines = self.__create_text()
Мы разделяем текст на строки ТОЛЬКО после создания инстанса (в ините?) или изменения контента (ЧЕРЕЗ СЕТТЕР).

2024-04-03 20:16 UTC, Ke1thuzad commented on src/gui_elements.py
> +                line_width += word_width
что мы делаем, когда у нас 2 повторяющиеся строчки в 2 разных условиях?? 







_(выносим за условие)_

2024-04-03 20:16 UTC, Ke1thuzad commented on src/gui_elements.py
> +        y_offset = self.position[1] + (self.position[3] - len(lines) * self.font_size) // 2
как же я обожаю магические вычисления даже без комментариев

2024-04-03 20:16 UTC, Ke1thuzad commented on src/gui_elements.py
> +        :param screen: Разрешение выводимого окна.
Запарил ты писать эту чушь.

2024-04-03 20:16 UTC, Ke1thuzad commented on src/gui_elements.py
> +        surface_lines = self.__create_text()
И потом используем эти созданные заранее значения, чтобы не создавать их по новой.

2024-04-03 20:16 UTC, Ke1thuzad commented on src/gui_elements.py
> +            img = self._create_button_img()
ВАУ! Супер бесполезная функция, ведь она НИЧЕГО не оптимизирует. То же самое, что и с текстом.

2024-04-03 20:16 UTC, Ke1thuzad commented on src/gui_elements.py
> +        :param font_style: Стиль текста. Задаётся битовой маской: 0b01 - жирный, 0b10 - курсив.
Добавил подчеркивание, но не поменял комментарий.

2024-04-03 20:16 UTC, Ke1thuzad commented on src/gui_elements.py
> +            font.set_underline(underline == 4)
здесь вообще не нужны ==, оно ЛИБО 0, ЛИБО >0.

2024-04-03 20:16 UTC, Ke1thuzad commented on src/gui_elements.py
> +        :param screen: Разрешение выводимого окна
Меняй

2024-04-03 20:18 UTC, Ecodrin commented on src/gui_elements.py
> +        y_offset = self.position[1] + (self.position[3] - len(lines) * self.font_size) // 2
очевидно

2024-04-03 20:19 UTC, Ecodrin commented on src/gui_elements.py
> +        :param screen: Разрешение выводимого окна.
**SmileFace**

2024-04-06 14:21 UTC, Ke1thuzad requested changes
Я уже устал один и тот же класс по 100 раз смотреть...

2024-04-06 14:21 UTC, Ke1thuzad commented on src/cell.py
>  import pygame
https://peps.python.org/pep-0008/#imports

2024-04-06 14:21 UTC, Ke1thuzad commented on src/gui_elements.py
> +        :param font_style: Стиль текста. Задаётся битовой маской: 0b01 - жирный, 0b10 - курсив, 0b100 - подчёркивание.
Ведущие нули где у 2 остальных?

2024-04-06 14:21 UTC, Ke1thuzad commented on src/gui_elements.py
> +            raise TypeError('content must be str')
Как is None связан с content must be str?
```suggestion
        if not isinstance(text, str):
            raise TypeError('Content must be a string type')
```

2024-04-06 14:21 UTC, Ke1thuzad commented on src/gui_elements.py
> +            raise TypeError('pos must be RectType')
Тоже самое.

2024-04-06 14:21 UTC, Ke1thuzad commented on src/gui_elements.py
> +        return self.font_style & 0b01
Ведущие нули и порядок по возрастанию: 1, 2, 4.

2024-04-06 14:21 UTC, Ke1thuzad commented on src/gui_elements.py
> +            y_offset += self.font_size
Научись писать комментарии...

2024-04-06 14:21 UTC, Ke1thuzad commented on src/gui_elements.py
> +            text_surface = font.render(text_line, True, self.text_colour)
Где keyword для True?

2024-04-06 14:21 UTC, Ke1thuzad commented on src/gui_elements.py
> +        :param  hitbox (rectangular):
Очень понятно и очевидно что это значит

2024-04-06 14:21 UTC, Ke1thuzad commented on src/gui_elements.py
> +        self.border_radius: int = border_radius
Радиус границ может быть **только** целым числом?

2024-04-06 14:21 UTC, Ke1thuzad commented on src/gui_elements.py
> +                 border_radius: int = 0) -> None:
Ниже

2024-04-06 14:21 UTC, Ke1thuzad commented on src/gui_elements.py
> +                self.button_texture = self.hover_texture
Какой смысл от этого, если ты уже в 176 строке меняешь цвет?

2024-04-06 14:21 UTC, Ke1thuzad commented on src/gui_elements.py
> +            self.button_texture = self.hover_texture
Кнопка меняет цвет на "hover", ЕСЛИ на нее не нажали еще...

2024-04-06 14:21 UTC, Ke1thuzad commented on src/gui_elements.py
> +                    img = pygame.transform.smoothscale(img, (self.hitbox[2], self.hitbox[3]))
Для корректного отображения желательно еще использовать convert_alpha
```suggestion
                    img = pygame.transform.smoothscale(img.convert_alpha(), (self.hitbox[2], self.hitbox[3]))
```

2024-04-06 14:21 UTC, Ke1thuzad commented on src/gui_elements.py
> +        return f'("{self._content}", {self.font_size}, {self.text_colour})'
Опять разные repr и str в 2 классах...

2024-04-06 14:21 UTC, Ke1thuzad commented on src/gui_elements.py
> +from cell import Clickable
https://peps.python.org/pep-0008/#imports
(должны быть пустые строки между разными типами импортов)

2024-04-06 17:57 UTC, Ke1thuzad requested changes
Парам-пам-пам...

2024-04-06 17:57 UTC, Ke1thuzad commented on src/gui_elements.py
> +        return f'("Text{self._content}", Size{self.font_size}, Colour{self.text_colour})'
Люблю слитный нечитаемый текст.
Эти мини-комментарии нужны только для неочевидных параметров.
Запринти в консоль что тебе выдает (БЕЗ ЭТИХ КОММЕНТАРИЕВ) и потом посмотри что неочевидно.

2024-04-06 17:57 UTC, Ke1thuzad commented on src/gui_elements.py
> +        return self.font_style & 0b0100
Ведущие нули...
И лишний ноль....

2024-04-06 17:57 UTC, Ke1thuzad commented on src/gui_elements.py
> +        # Проверка на коллизию мышки с кнопкой.
СПАСИБО ПАПАША ЗА ТАКОЙ ПОНЯТНЫЙ КОММЕНТАРИЙ
А ЗАЧЕМ ЭТО???
Здесь он вообще не особо нужен.

2024-04-06 17:57 UTC, Ke1thuzad commented on src/gui_elements.py
>                  self.button_texture = self.click_texture
Наслаждайся (НЕ) своим решением элементарной проблемы.
```suggestion
            if event.type == pygame.MOUSEBUTTONDOWN:
                self.button_texture = self.click_texture
            else:
                self.button_texture = self.hover_texture
```

2024-04-06 17:57 UTC, Ke1thuzad commented on src/gui_elements.py
>              # Кэшировние изображений, которые уже были зарендерины.
```suggestion
            # Кэшировние изображений, которые уже были зарендерены.
```

2024-04-06 17:57 UTC, Ke1thuzad commented on src/gui_elements.py
>                  img = self._image_cache[self.button_texture]
Утечка памяти...

_P.S при кешировании новых изображений, старые остаются в памяти и занимают лишнее место..._

2024-04-06 17:57 UTC, Ke1thuzad commented on src/gui_elements.py
> +                    img = pygame.transform.smoothscale(img.convert_alpha(), (self.hitbox[2], self.hitbox[3]))
```suggestion
                    img = pygame.transform.smoothscale(img, (self.hitbox[2], self.hitbox[3]))
```
Не увидел, что ты сверху и так это делаешь. Мог бы и сказать мне.
_(признайся, скопировал с какого-нибудь stackoverflow и даже не смотрел?)_

2024-04-06 18:41 UTC, Ke1thuzad requested changes
Bruh moment

2024-04-06 18:41 UTC, Ke1thuzad commented on src/gui_elements.py
> +        return self.font_style & 0b01
нет 2 нуля...

2024-04-06 18:41 UTC, Ke1thuzad commented on src/gui_elements.py
> +        return f'"Text {self._content}\nSize {self.font_size}\nColour {self.text_colour}'
Оо да... 
Быстрее захламляем консоль с помощью \n
Давай так, в repr все параметры, чтобы с помощью копирования всего repr можно было создать такую же переменную с такими же параметрами.
В str понятную инфу без \n.

2024-04-06 18:41 UTC, Ke1thuzad commented on src/gui_elements.py
> +        self.inner_text.position = center_relative_to(self.inner_text.position, self.hitbox)
Ооо да, центруем каждый кадр, чтобы создать бесполезную нагрузку...

2024-04-06 18:41 UTC, Ke1thuzad commented on src/gui_elements.py
> +                    self._image_cache.clear()
Весь смысл оптимизации через кэш исчезает, потому что кэш очищается каждый фрейм 😋

2024-04-06 18:41 UTC, Ke1thuzad commented on src/gui_elements.py
> +                f'\nhov_tex {self.hover_texture}\nclick_tex {self.click_texture})\n')
Тоже самое

2024-04-06 18:41 UTC, Ke1thuzad commented on src/gui_elements.py
> +        if isinstance(self.button_texture, pygame.color.Color):
Необязательно писать pygame.color.Color.
Можно pygame.Color

2024-04-09 06:09 UTC, Ecodrin approved these changes

2024-04-09 06:09 UTC, Ecodrin commented on src/gui_elements.py
> +        :param screen: Разрешение выводимого окна
**SmileFace**

2024-04-09 14:53 UTC, Ke1thuzad approved these changes
Lgtm

2024-04-09 15:55 UTC, merged